import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { letters, teachers } from './data/teachers'
import type { ArchiveLetter, TeacherProfile } from './types/teacher'
import './styles.css'

const go = (to: string) => { history.pushState({}, '', to); dispatchEvent(new PopStateEvent('popstate')) }
const Back = ({ to = '/' }: { to?: string }) => <button className="archive-back" onClick={() => go(to)}>← BACK TO ARCHIVE</button>
const Arrow = () => <span aria-hidden="true">→</span>
function Header() { return <header className="nav inner-nav"><button className="brand" onClick={() => go('/')}>THE TEACHER<br />ARCHIVE <sup>2026</sup></button><button className="nav-word" onClick={() => go('/teachers')}>THE FILES</button><button className="nav-word" onClick={() => go('/lessons')}>LESSONS</button><button className="nav-word" onClick={() => go('/memories')}>MEMORIES</button><button className="nav-word" onClick={() => go('/letters')}>LETTERS</button></header> }
function Footer() { return <footer><p>THE TEACHER ARCHIVE <span>—</span> 2026</p><p>We never really leave the lessons.</p><button onClick={() => go('/')}>BACK TO THE FIRST PAGE ↑</button></footer> }

function Home() { return <><Header /><section className="entry home-entry"><div className="entry-meta">PERSONAL COLLECTION &nbsp; / &nbsp; TEACHER'S DAY 2026</div><div className="stamp"><span className="stamp-ring" /><b>PRESERVED</b><small>09.05.26</small><em>kept with care</em></div><p className="eyebrow">A collection of the people, lessons, and moments that stayed.</p><h1>THE<br /><i>TEACHER</i><br />ARCHIVE</h1><div className="entry-bottom"><button className="open-file" onClick={() => go('/teachers')}>OPEN THE ARCHIVE <Arrow /></button><p>Some people teach a subject.<br />Some people become part of the story.</p></div></section><section className="intro section-pad"><p className="section-number">01 / A SMALL ACT OF REMEMBERING</p><div className="intro-copy"><h2>We eventually leave<br />the classroom.</h2><p>But some lessons follow us quietly, into the work we choose, the questions we ask, and the people we become.</p></div><p className="hand-note">not a tribute.<br />a record of what remains.</p></section><section className="route-preview files-preview" onClick={() => go('/teachers')}><p className="section-number">02 / THE PEOPLE</p><h2>THE <i>TEACHER</i><br />FILES</h2><p>Open the collection of people who made an ordinary classroom a place worth remembering.</p><p className="hand-note section-note">names become anchors<br />when time moves on.</p><button onClick={(event) => { event.stopPropagation(); go('/teachers') }}>ENTER THE FILES <Arrow /></button></section><section className="route-preview lesson-preview" onClick={() => go('/lessons')}><p className="section-number">03 / WHAT STAYED</p><h2>THE LESSONS<br /><i>I CARRY</i></h2><p>A quiet room reserved for the principles that outlived their original lessons.</p><p className="hand-note section-note">some teaching turns<br />into instinct.</p><button onClick={(event) => { event.stopPropagation(); go('/lessons') }}>READ THE LESSONS <Arrow /></button></section><section className="route-preview memory-preview" onClick={() => go('/memories')}><p className="section-number">04 / THE MEMORY ROOM</p><h2>MOMENTS<br /><i>THAT STAYED</i></h2><p>A prepared space for the real memories, small scenes, and classroom fragments still worth keeping.</p><p className="hand-note section-note">not everything important<br />arrives loudly.</p><button onClick={(event) => { event.stopPropagation(); go('/memories') }}>ENTER MEMORIES <Arrow /></button></section><section className="route-preview letter-preview" onClick={() => go('/letters')}><p className="section-number">05 / WORDS THAT TOOK THEIR TIME</p><h2>LETTERS<br /><i>NEVER SENT</i></h2><p>Fourteen preserved pieces, each written for the person who helped shape the way forward.</p><p className="hand-note section-note">the words waited.<br />now they have a room.</p><button onClick={(event) => { event.stopPropagation(); go('/letters') }}>OPEN THE LETTERS <Arrow /></button></section><Footer /></> }

function Teachers() { return <><Header /><main className="archive-page"><Back /><p className="section-number">THE TEACHER ARCHIVE / FILE INDEX</p><h1 className="page-title">THE <i>TEACHER</i><br />FILES</h1><p className="page-intro">Each file is a small record of presence: a name, a dedication, and the gratitude that stayed.</p><div className="file-index">{teachers.map((teacher, index) => <button key={teacher.id} className="file-row" onClick={() => go(`/teacher/${encodeURIComponent(teacher.id)}`)}><span>FILE / {String(index + 1).padStart(2, '0')}</span><b>{teacher.name}</b><em>{teacher.designation ?? 'PERSONAL ARCHIVE'}</em><Arrow /></button>)}</div></main><Footer /></> }
function TeacherPage({ teacher }: { teacher: TeacherProfile }) { const letter = letters.find((item) => item.teacherId === teacher.id)!; return <><Header /><main className="archive-page teacher-page"><Back to="/teachers" /><p className="section-number">PERSONAL FILE / {teacher.id.toUpperCase()}</p><div className="teacher-hero"><div className="monogram">{teacher.initials}</div><div><h1 className="page-title">{teacher.name}</h1><p className="teacher-role">{teacher.designation ?? 'A PRESERVED PERSONAL ARCHIVE'}</p><p className="page-intro">Some people teach a subject. Some people become part of the story.</p></div></div><section className="inside-file"><p className="section-number">THE WRITTEN RECORD</p><h2>A note kept<br /><i>for you.</i></h2><p>One personal dedication has been preserved in this file.</p><button className="archival-cta" onClick={() => go(`/letters/${letter.id}`)}>OPEN THE LETTER <Arrow /></button></section><section className="empty-room"><p className="section-number">THE LESSONS I CARRY</p><h2>A space held<br />with care.</h2><p>Lessons and memories will be added to this archive as they are recorded.</p></section></main><Footer /></> }
function Letters() { return <><Header /><main className="archive-page letters-page"><Back /><p className="section-number">THE TEACHER ARCHIVE / WRITTEN COLLECTION</p><h1 className="page-title">LETTERS<br /><i>NEVER SENT</i></h1><p className="page-intro">Personal poems and dedications—preserved exactly as they were written.</p><div className="letter-grid">{letters.map((letter, index) => <button className="letter-file" key={letter.id} onClick={() => go(`/letters/${letter.id}`)}><span>{String(index + 1).padStart(2, '0')} / {letter.type.toUpperCase()}</span><b>{letter.title}</b><em>OPEN LETTER <Arrow /></em></button>)}</div></main><Footer /></> }
function LetterPage({ letter }: { letter: ArchiveLetter }) { const teacher = teachers.find((item) => item.id === letter.teacherId); return <><Header /><main className="archive-page letter-page"><Back to="/letters" /><article className="opened-letter"><p className="section-number">ARCHIVE LETTER / {letter.type.toUpperCase()}</p><h1 className="page-title">{letter.title}</h1><p className="letter-recipient">A preserved dedication for {teacher?.name}</p><div className="letter-rule" /><p className="letter-text">{letter.content}</p><p className="letter-mark">THE TEACHER ARCHIVE<br />2026</p></article></main><Footer /></> }
function EmptyArchive({ title, label }: { title: string; label: string }) { return <><Header /><main className="archive-page empty-page"><Back /><p className="section-number">{label}</p><h1 className="page-title">{title}</h1><div className="empty-room"><p>This room has been prepared for future archive records.</p><p className="small-copy">Nothing has been invented to fill it. When a real lesson or memory is ready to be preserved, it will live here.</p></div></main><Footer /></> }
function Router() { const [path, setPath] = useState(location.pathname); useEffect(() => { const update = () => setPath(location.pathname); addEventListener('popstate', update); return () => removeEventListener('popstate', update) }, []); const teacher = teachers.find((item) => item.id === decodeURIComponent(path.replace('/teacher/', ''))); const letter = letters.find((item) => item.id === path.replace('/letters/', '')); let page = <Home />; if (path === '/teachers') page = <Teachers />; else if (path === '/letters') page = <Letters />; else if (path === '/lessons') page = <EmptyArchive label="THE LESSONS I CARRY" title="LESSONS TO BE KEPT" />; else if (path === '/memories') page = <EmptyArchive label="THE MEMORY ROOM" title="MOMENTS TO REMEMBER" />; else if (path.startsWith('/teacher/') && teacher) page = <TeacherPage teacher={teacher} />; else if (path.startsWith('/letters/') && letter) page = <LetterPage letter={letter} />; return <div key={path} className="page-transition">{page}</div> }
createRoot(document.getElementById('root')!).render(<Router />)
